# fly.toml app configuration file generated for personal-blog-ha4cda on 2025-09-01T02:01:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-blog-ha4cda'
primary_region = 'lax'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
